// Mocks generated by Mockito 5.0.7 from annotations
// in fordev/test/ui/pages/login_page_test.dart.
// Do not manually edit this file.

import 'package:fordev/ui/pages/login/login_presenter.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [LoginPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class LoginPresenterMock extends _i1.Mock implements _i2.LoginPresenter {
  LoginPresenterMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void validateEmail(String? email) =>
      super.noSuchMethod(Invocation.method(#validateEmail, [email]),
          returnValueForMissingStub: null);
  @override
  void validatePassword(String? password) =>
      super.noSuchMethod(Invocation.method(#validatePassword, [password]),
          returnValueForMissingStub: null);
}
