// Mocks generated by Mockito 5.0.7 from annotations
// in fordev/test/ui/pages/splash_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'splash_page_test.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [SplashPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class SplashPresenterMock extends _i1.Mock implements _i2.SplashPresenter {
  SplashPresenterMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<String?> get navigateToStream =>
      (super.noSuchMethod(Invocation.getter(#navigateToStream),
          returnValue: Stream<String?>.empty()) as _i3.Stream<String?>);
  @override
  _i3.Future<void> loadCurrentAccount() =>
      (super.noSuchMethod(Invocation.method(#loadCurrentAccount, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i3.Future<void>);
}
