// Mocks generated by Mockito 5.0.10 from annotations
// in fordev/test/data/usecases/local_load_surveys/local_load_surveys_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:fordev/data/cache/fetch_cache_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [FetchCacheStorage].
///
/// See the documentation for Mockito's code generation for more information.
class FetchCacheStorageMock extends _i1.Mock implements _i2.FetchCacheStorage {
  FetchCacheStorageMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> fetch(String? key) =>
      (super.noSuchMethod(Invocation.method(#fetch, [key]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
}
