// Mocks generated by Mockito 5.0.10 from annotations
// in fordev/test/data/usecases/local_load_surveys/local_load_surveys_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'local_load_surveys_test.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [FetchCacheStorage].
///
/// See the documentation for Mockito's code generation for more information.
class FetchCacheStorageMock extends _i1.Mock implements _i2.FetchCacheStorage {
  @override
  _i3.Future<void> fetch(String? key) =>
      (super.noSuchMethod(Invocation.method(#fetch, [key]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i3.Future<void>);
}
