// Mocks generated by Mockito 5.0.10 from annotations
// in fordev/test/presentation/presenters/splash/getx_splash_presenter_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:fordev/domain/entities/account_entity.dart' as _i2;
import 'package:fordev/domain/usecases/account/load_current_account.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeAccountEntity extends _i1.Fake implements _i2.AccountEntity {}

/// A class which mocks [LoadCurrentAccount].
///
/// See the documentation for Mockito's code generation for more information.
class LoadCreationAccountMock extends _i1.Mock
    implements _i3.LoadCurrentAccount {
  @override
  _i4.Future<_i2.AccountEntity> load() => (super.noSuchMethod(
          Invocation.method(#load, []),
          returnValue: Future<_i2.AccountEntity>.value(_FakeAccountEntity()))
      as _i4.Future<_i2.AccountEntity>);
}
