// Mocks generated by Mockito 5.0.8 from annotations
// in fordev/test/presentation/presenters/getx_sign_up_presenter_test.dart.
// Do not manually edit this file.

import 'package:fordev/presentation/dependencies/validation.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Validation].
///
/// See the documentation for Mockito's code generation for more information.
class ValidationMock extends _i1.Mock implements _i2.Validation {
  @override
  _i2.ValidationErro? validate({String? field, String? value}) =>
      (super.noSuchMethod(
              Invocation.method(#validate, [], {#field: field, #value: value}))
          as _i2.ValidationErro?);
}
