// Mocks generated by Mockito 5.0.7 from annotations
// in fordev/test/presentation/presenters/stream_login_presenter_test.dart.
// Do not manually edit this file.

import 'package:fordev/presentation/dependencies/validation.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [Validation].
///
/// See the documentation for Mockito's code generation for more information.
class ValidationMock extends _i1.Mock implements _i2.Validation {
  @override
  String? validate({String? field, String? value}) => (super.noSuchMethod(
          Invocation.method(#validate, [], {#field: field, #value: value}))
      as String?);
}
